### ISSUE TITLE
Support for node v6

### ISSUE THREAD

**Issue by dhessler** [fetch-auto/node-config-cryptex#1]
I am trying to use this library for a serverless deployment (to Lambda with node v6.10).

I see that node v8 is required because of async/await usage.
It would be great if this module was distributed transpiled down to it's lowest supported node version, so that it could reach a greater audience.

What do you think about transpiling the codebase, or simply using basic promises instead of async/await?

**Comment by gcoombe** [comment]
Hey @dhessler, no problem I'll look into creating a transpiled version over the weekend.

**Comment by dhessler** [comment]
@gcoombe transpiling is a pain understandably, so for my own use I went ahead and made some quick adjustments for node v4 support (minimum supported version given the dependencies). if you'd like to go that route instead i can open a PR from https://github.com/dhessler/node-config-cryptex.

**Comment by gcoombe** [comment]
Hey @dhessler thanks for doing this, but as you noticed I have decided to just add a babel step.  My reasoning is that we're trying to embrace async/await over here in the bulk for our code base so I would like to retain this in this module.

**Comment by gcoombe** [comment]
Closed in #2
